version: "3"
services:
  app:
    user: root
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 3000:3000
      - 443:443
      - 80:80
    networks:
      app_net:
        ipv4_address: 10.10.10.102
    depends_on:
      app_db:
        condition: service_healthy
    env_file:
      - .env
  app_db:
    image: postgres:15.4
    container_name: app_db
    environment:
      PGPORT: 5434
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "fitness_app"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 5s
      interval: 1s
      timeout: 5s
      retries: 5
    networks:
      app_net:
        ipv4_address: 10.10.10.103

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
